"""Utility functions and validation."""
from app.utils.validation import (
    sanitize_string,
    sanitize_html,
    validate_username,
    validate_password,
    validate_image_url,
    validate_title,
    validate_description,
    validate_search_query,
    validate_price,
    validate_quantity,
    validate_page,
    MAX_USERNAME_LENGTH,
    MAX_EMAIL_LENGTH,
    MAX_PASSWORD_LENGTH,
    MAX_TITLE_LENGTH,
    MAX_DESCRIPTION_LENGTH,
    MAX_URL_LENGTH,
    MAX_SEARCH_LENGTH,
)
from app.utils.rate_limit import (
    get_rate_limit_key,
    get_user_rate_limit_key,
    get_ip_rate_limit_key,
)

__all__ = [
    "sanitize_string",
    "sanitize_html",
    "validate_username",
    "validate_password",
    "validate_image_url",
    "validate_title",
    "validate_description",
    "validate_search_query",
    "validate_price",
    "validate_quantity",
    "validate_page",
    "MAX_USERNAME_LENGTH",
    "MAX_EMAIL_LENGTH",
    "MAX_PASSWORD_LENGTH",
    "MAX_TITLE_LENGTH",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_URL_LENGTH",
    "MAX_SEARCH_LENGTH",
    "get_rate_limit_key",
    "get_user_rate_limit_key",
    "get_ip_rate_limit_key",
]
